# Generated by Django 4.2.7 on 2024-04-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_systems', '0003_rename_meal_day_meals_rename_day_dietplan_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='minimum_difference_weight',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='name',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium')], max_length=50),
        ),
    ]
