# Generated by Django 4.2.7 on 2024-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_systems', '0004_dietplan_minimum_difference_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='maximum_difference_weight',
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
    ]
