# Generated by Django 4.2.7 on 2024-02-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.PositiveIntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
