# Generated by Django 4.2.7 on 2024-03-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_gender_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
