# Generated by Django 4.2.7 on 2024-03-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='system',
        ),
    ]
