# Generated by Django 4.2.7 on 2024-04-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealDetail100g',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='meals')),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbs', models.FloatField()),
                ('calories', models.FloatField()),
            ],
        ),
    ]
