# Generated by Django 4.2.7 on 2024-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdetail100g',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
