# Generated by Django 4.2.7 on 2024-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_details', '0002_alter_mealdetail100g_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdetail100g',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mealdetail100g',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mealdetail100g',
            name='fats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mealdetail100g',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mealdetail100g',
            name='protein',
            field=models.IntegerField(),
        ),
    ]
