# Generated by Django 4.2.7 on 2024-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_details', '0003_alter_mealdetail100g_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdetail100g',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mealdetail100g',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mealdetail100g',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mealdetail100g',
            name='protein',
            field=models.FloatField(),
        ),
    ]
